version: '3.8'

services:
  litterlotto_web_frontend:
    image: 'registry.digitalocean.com/litter-lotto/litter-lotto_web_frontend:latest'
    tty: true
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.litterlotto_web_frontend.loadbalancer.server.port=3000"
      - "traefik.http.services.litterlotto_web_frontend.loadbalancer.sticky=true"

      - "traefik.http.routers.litterlotto-secure.entrypoints=web-secure"
      - "traefik.http.routers.litterlotto-secure.rule=Host(`litterlotto.com`,`www.litterlotto.com`)"
      - "traefik.http.routers.litterlotto-secure.tls.certresolver=le"
      - "traefik.http.routers.litterlotto-secure.tls=true"

      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://(?:www\\.)?(.+)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.email=joshualyness@outlook.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--log=true"
      - "--log.filepath=/var/log/traefik.log"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
