version: '3.8'

services:
  litter-lotto_web_frontend:
    container_name: 'litter-lotto_web_frontend'
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/app
    ports:
      - "3000:3000"