FROM node:16.14.2-alpine as builder

# create & set working directory
WORKDIR /app

# copy source files
COPY package.json yarn.lock ./

# install dependencies
RUN yarn

#copy files
COPY . ./

# start app
EXPOSE 3000

RUN yarn build

CMD ["yarn", "run", "start"]