// Generated by https://quicktype.io

export interface BinWithInfo {
    tagged_bin_group: TaggedBinGroup;
    location: Location;
    tagged_bin_type: TaggedBinType;
    binId: string;
}

export interface Location {
    default_lon: number;
    default_lat: number;
    actual_lon: null;
    actual_lat: null;
}

export interface TaggedBinGroup {
    description: string;
    completion_footer: string;
    completion_intro: string;
    completion_title: string;
    completion_footer_title: string;
    title: string;
    logoURL: string;
    id: string;
    card: {
        actionButton: string;
        cardImage: string;
        cardSubTitle: string;
        cardTitle: string;
    };
}

export interface TaggedBinType {
    tagged_bin_group: string;
    footer_title: string;
    wasteTypes: string[];
    title: string;
    footer: string;
    intro: string;
    warning: string;
    banner_image: string;
    id: string;
}
